"""v0_2_schema_full_redesign

Revision ID: a6b46fee90c0
Revises: 0002
Create Date: 2026-05-21 17:08:24.535771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b46fee90c0'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_permissions_resource', 'permissions', ['resource'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_providers_kind', 'providers', ['kind'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_settings_scope_key', 'settings', ['scope', 'key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_version', sa.Integer(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('apps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('qpm_limit', sa.Integer(), nullable=True),
    sa.Column('qpd_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_key')
    )
    op.create_index('ix_apps_owner', 'apps', ['owner_user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('defaults', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_models_kind', 'models', ['kind'], unique=False)
    op.create_index('uq_models_provider_code', 'models', ['provider_id', 'code'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='pk_role_permissions')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='pk_user_roles')
    )
    op.create_table('agents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=True),
    sa.Column('local_class_path', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('default_model_id', sa.BigInteger(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_key')
    )
    op.create_index('ix_agents_enabled', 'agents', ['enabled'], unique=False)
    op.create_index('ix_agents_source', 'agents', ['source'], unique=False)
    op.create_table('app_agents',
    sa.Column('app_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_id', 'agent_id', name='pk_app_agents')
    )
    op.create_table('embed_configs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('embed_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.BigInteger(), nullable=False),
    sa.Column('allowed_origins', sa.JSON(), nullable=True),
    sa.Column('ui_config', sa.JSON(), nullable=True),
    sa.Column('behavior', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embed_key')
    )
    op.create_index('ix_embed_configs_agent', 'embed_configs', ['agent_id'], unique=False)
    op.create_index('ix_embed_configs_app', 'embed_configs', ['app_id'], unique=False)
    op.add_column('api_keys', sa.Column('created_by_user_id', sa.BigInteger(), nullable=True))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('api_keys_app_id_key'), 'api_keys', type_='unique')
    op.create_index('ix_api_keys_app', 'api_keys', ['app_id'], unique=False)
    op.create_index('ix_api_keys_created_by', 'api_keys', ['created_by_user_id'], unique=False)
    # ── backfill：把 v0.1 散落的 distinct app_id 字符串导入 apps 表，让 FK 加得上 ──
    # 雪花 ID 用 PG 算（gen_random_uuid 不行因为是 bigint）—— 用 nextval 简化为时间戳 + 随机
    op.execute("""
        INSERT INTO apps (id, app_key, name, status, created_at, updated_at)
        SELECT
            (extract(epoch from now()) * 1000)::bigint * 4194304 + (random() * 4194304)::bigint AS id,
            sub.app_id AS app_key,
            sub.app_id AS name,
            'active' AS status,
            now() AS created_at,
            now() AS updated_at
        FROM (
            SELECT DISTINCT app_id FROM api_keys WHERE app_id IS NOT NULL
            UNION
            SELECT DISTINCT app_id FROM conversations WHERE app_id IS NOT NULL
            UNION
            SELECT DISTINCT app_id FROM call_logs WHERE app_id IS NOT NULL
            UNION
            SELECT DISTINCT app_id FROM tasks WHERE app_id IS NOT NULL
        ) AS sub
        ON CONFLICT (app_key) DO NOTHING
    """)
    op.create_foreign_key(None, 'api_keys', 'apps', ['app_id'], ['app_key'], ondelete='CASCADE')
    op.create_foreign_key(None, 'api_keys', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('api_keys', 'created_by_id')
    op.add_column('call_logs', sa.Column('api_key_id', sa.BigInteger(), nullable=True))
    op.add_column('call_logs', sa.Column('error_class', sa.String(length=64), nullable=True))
    op.create_index('ix_call_logs_api_key', 'call_logs', ['api_key_id'], unique=False)
    # 注：call_logs/conversations 的 agent_key FK 推到 P5（agents 表由 registry sync 填充）
    op.create_foreign_key(None, 'call_logs', 'api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'call_logs', 'apps', ['app_id'], ['app_key'], ondelete='CASCADE')
    # autogenerate 误判：HNSW 索引（pgvector 扩展）不在 SQLAlchemy metadata 里，但实际 PG 中存在；保留不动
    op.create_foreign_key(None, 'conversations', 'apps', ['app_id'], ['app_key'], ondelete='CASCADE')
    op.drop_column('conversations', 'provider')
    op.create_foreign_key(None, 'tasks', 'apps', ['app_id'], ['app_key'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.add_column('conversations', sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # HNSW 索引 downgrade 不需要操作（upgrade 时也没动）
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.drop_index('ix_call_logs_api_key', table_name='call_logs')
    op.drop_column('call_logs', 'error_class')
    op.drop_column('call_logs', 'api_key_id')
    op.add_column('api_keys', sa.Column('created_by_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index('ix_api_keys_created_by', table_name='api_keys')
    op.drop_index('ix_api_keys_app', table_name='api_keys')
    op.create_unique_constraint(op.f('api_keys_app_id_key'), 'api_keys', ['app_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'created_by_user_id')
    op.drop_index('ix_embed_configs_app', table_name='embed_configs')
    op.drop_index('ix_embed_configs_agent', table_name='embed_configs')
    op.drop_table('embed_configs')
    op.drop_table('app_agents')
    op.drop_index('ix_agents_source', table_name='agents')
    op.drop_index('ix_agents_enabled', table_name='agents')
    op.drop_table('agents')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('uq_models_provider_code', table_name='models')
    op.drop_index('ix_models_kind', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_apps_owner', table_name='apps')
    op.drop_table('apps')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_settings_scope_key', table_name='settings')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_index('ix_providers_kind', table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_permissions_resource', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
